ports:
  - port: 8080
tasks:
  - name: Dev server
    before: cp .dist.env .env
    init: |
      composer install --quiet --working-dir=src
      docker compose build --quiet --pull --no-cache
    command: |
      docker compose up -d
      docker compose logs -f
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: true
    addBadge: true
jetbrains:
  intellij:
    prebuilds:
      version: stable
